version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=test"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"